### ISSUE TITLE
File which contain verbatim environment cause a runtime error

### ISSUE THREAD

**Issue by kn1cht** [fgborges/textlint-plugin-latex2e#26]
## 環境
- textlint 11.6.1
- textlint-plugin-latex2e 0.3.1

## 現象
`verbatim`環境があるファイルを処理するとエラーになります。

```bash
$ cat test.tex               
\begin{verbatim}
This is a LaTeX file.
\end{verbatim}
$ npx textlint test.tex
✖ Error
Cannot read property 'loc' of undefined

✖ Stack trace
TypeError: Cannot read property 'loc' of undefined
    at validate (.../node_modules/@textlint/kernel/lib/kernel/src/context/TextlintSourceCodeImpl.js:24:14)
    at new TextlintSourceCodeImpl (.../node_modules/@textlint/kernel/lib/kernel/src/context/TextlintSourceCodeImpl.js:44:9)
    at TextlintKernel._parallelProcess (.../node_modules/@textlint/kernel/lib/kernel/src/textlint-kernel.js:139:26)
    at .../node_modules/@textlint/kernel/lib/kernel/src/textlint-kernel.js:86:26
```

以前のバージョンでは問題が生じていませんでしたので、 #24 で入ったverbatim関連の変更によると考えられます。

## 原因
textlintカーネル自体がエラーを出しており、不正なASTが出力されているようです。
以下は上記文字列のパース結果です。

```json
{
  "loc": {
    "end": { "column": 18, "line": 3 },
    "start": { "column": 0,  "line": 1 }
  },
  "range": [ 0, 61 ],
  "raw": "\\begin{verbatim}\n    T\nhis is a LaTeX file.\n    \\end{verbatim}",
  "type": "Document",
  "children": [
    {
      "loc": {
        "end": { "column": 18, "line": 3 },
        "start": { "column": 0, "line": 1 }
      },
      "range": [ 0, 61 ],
      "raw": "\\begin{verbatim}\n    This is a LaTeX file.\n    \\end{verbatim}",
      "type": "CodeBlock",
      "value": [
        {
          "loc": {
            "end": { "column": 4, "line": 3 },
            "start": { "column": 16, "line": 1 }
          },
          "range": [ 16, 47 ],
          "raw": "\n    This is a LaTeX file.\n    ",
          "type": "Str",
          "value": "\n    This is a LaTeX file.\n    "
        }
      ]
    }
  ]
}
```

特におかしい点はないように見えますが、`@textlint/ast-tester`に渡すとエラーとなります。

```js
● Parsimmon AST › verbatim environment

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      "string"
    Received:
      "object"

    Difference:

    - Expected
    + Received

    - string
    + object

      141 |     const ast = LaTeX.Program.tryParse(code);
      142 |     console.log(JSON.stringify(parse(code)));
    > 143 |     ASTTester.test(parse(code));
          |               ^
      144 |     expect(ast.value[0].value.name).toBe("verbatim");
      145 |     // ast.value[1] is a text node ("\n        ")
      146 |     expect(ast.value[2].value.name).toBe("verbatim*");
```

**Comment by kn1cht** [comment]
間違いを見つけました。CodeBlockの`value`はstringでなければいけません。

[textlint AST explorer](https://textlint.github.io/astexplorer/)の結果を見るに、CodeBlock内に何を書いてもchildrenノードが作られず、valueに文字列がそのまま入るようです。
<img width="1039" alt="スクリーンショット 0002-01-17 14 21 15" src="https://user-images.githubusercontent.com/16277200/72586342-b2dafc80-3934-11ea-824f-aaa5a8f19a1b.png">

この動作に合うように`latex-to-ast/index.ts`を修正すれば良いと思われます。修正ができましたらPull Requestします。

https://github.com/pddg/textlint-plugin-latex2e/blob/5b839c828e9d0cdbb293b3283e9e2aa436271899/src/latex-to-ast/index.ts#L177-L189

**Comment by pddg** [comment]
@kn1cht 報告ありがとうございます．私の実装のミスですね．
ただ妙ですね…… #24 での変更の際，手元で変更済みのパッケージをlinkしてベンチマークを行ったたのですが，その際エラーは見られませんでした．

もしかしたらベンチマーク自体がうまくいっていなかったのかもしれません．もしよろしければ，そのPR時に #24 で使ったベンチマークを用いて再度性能を評価していただけませんか？

**Comment by kn1cht** [comment]
@pddg 承知いたしました
