### ISSUE TITLE
latex-to-ast.js causes error in v0.3.3 at npm

### ISSUE THREAD

**Issue by kn1cht** [fgborges/textlint-plugin-latex2e#29]
## 現象
v0.3.3で，`latex-utensils`がないとのエラーが出て実行できません

```bash
$ textlint foo.tex
✖ Error
Cannot find module 'latex-utensils'

✖ Stack trace
Error: Cannot find module 'latex-utensils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/textlint-plugin-latex2e/lib/latex-to-ast.js:21:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/textlint-plugin-latex2e/lib/LaTeXProcessor.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
```

## 原因
`npm publish`時に，何らかの原因で開発中の`latex-to-ast.js`がlibフォルダに含まれてしまったようです．
@fgborges `latex-to-ast.js`が入っていないバージョンをアップロードしていただけますでしょうか？

## Workaround
node_modulesフォルダから`latex-to-ast.js`を探して削除すれば動作します．

**Comment by fgborges** [comment]
ご報告ありがとうございます．今晩アップロードしなおします．

**Comment by fgborges** [comment]
お手数をお掛けしました．0.3.4をアップロードしました．問題がないようでしたら，このIssueを閉じていただけますか?

**Comment by kn1cht** [comment]
0.3.4で動作を確認しました．ありがとうございました．
